# Site settings
title: Daniel Bell
email: djbell70@gmail.com
description: Web Design + Development
baseurl: "" 
url: "http://danieljbell.github.io" 
twitter_username: DeveloperDB
github_username:  danieljbell
codepen_username:  djbell

# Build settings
markdown: kramdown
exclude: ['package.json', 'node_modules', 'gulpfile.js']
permalink: pretty

collections:
  posts:
    permalink: /blog/:categories/:title/