# Site settings
title: Daniel Bell
email: djbell70@gmail.com
description: Print, Web, Interactive<br>Design + Development
url: "http://danieljbell.github.io" 
twitter_username: DeveloperDB
github_username:  danieljbell
codepen_username:  djbell

# Build settings
markdown: kramdown

exclude: ['Gruntfile.js', 'package.json', 'node_modules']
permalink: pretty
